teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 1.0
    scale_linear_turbo:
      x: 40.0

    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 0.7508
    scale_angular_turbo:
      yaw: 0.05510

    require_enable_button: false
        # enable_button: 7  # L2 shoulder button
    enable_turbo_button: 5  # L1 shoulder button
